language: bash

notifications:
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp

dist: trusty
sudo: required

install:
  - cd /home/travis/build
  - mkdir get && cd get
  - curl -sSL https://get.mapic.io | sh
  - sudo rm -rf /home/travis/build/get/mapic/engine
  - sudo cp -r /home/travis/build/mapic/engine /home/travis/build/get/mapic/engine
  - cd /home/travis/build/get/mapic/cli
  - sudo bash mapic-cli.sh
  - sudo mapic version
  - sudo mapic config set MAPIC_USER_EMAIL travis@mapic.io
  - sudo mapic config set MAPIC_DOMAIN localhost
  - sudo mapic ssl create
  - sudo mapic travis stack

script:
  - sudo mapic travis start
  - sudo mapic test engine